podTemplate(containers: [
     containerTemplate(name: 'deploy', image: 'dtzar/helm-kubectl', ttyEnabled: true, command: 'sleep 100000000000'),
     containerTemplate(name: 'build', image: 'benhall/dind-jenkins-agent', ttyEnabled: true, command: 'sleep 100000000000')
  ],
  volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')] )
  {
    node(POD_LABEL) {
        git branch: 'main',
        credentialsId: 'jenkins-user-github',
        url: 'https://github.com/ishais123/moon.git'
        container('build') {
            stage('build') {
                sh "ls -la"
                GIT_TAG = sh(returnStdout: true, script: "git tag --contains | head -1").trim()
                if ( GIT_TAG ){
                    dir('time-service') {
                      sh "sed -i '14s/#//' /etc/default/docker"
                      sh "service docker restart"
                      sh 'ping -c 3 github.com'
                      sh 'ping -c 3 8.8.8.8'
                      sh "docker build -t ishais/time-service:${GIT_TAG} ."
                    }
                }
                else{
                    dir('time-service') {
                      sh "echo nameserver 8.8.8.8 > /etc/resolv.conf"
                      sh 'ping -c 3 github.com'
                      sh 'ping -c 3 8.8.8.8'
                      sh "docker build -t ishais/time-service:latest ."
                    }
                }
                sh "docker images"
            }
        }
        container('deploy') {
            stage('deploy') {
                sh "kubectl get nodes"
            }
        }
    }
  }